house_controller:
    resource:
        path: ../src/Booking/House/Infrastructure/Symfony/
        namespace: Booking\House\Infrastructure\Symfony
    type: attribute
    
user_controller:
    resource:
        path: ../src/Booking/User/Presentation/
        namespace: Booking\User\Presentation
    type: attribute
